In [11]:
import tensorflow as tf 
import numpy as np 

from PIL import Image 

import os
from os import listdir
from os.path import isfile, join
import shutil

In [3]:
data_dir ='/home/dongsung/Downloads/caltech-256-image-dataset/256_ObjectCategories/'

In [22]:
# image data file handling

object_categories = listdir(data_dir)
object_categories.sort()
# for i in range(len(object_categories)):
#     print (object_categories[i])

category_dir = join(data_dir,object_categories[0])
print(category_dir)

# store full path
onlyfiles = [f for f in listdir(category_dir) if isfile(join(category_dir, f))]

print(len(onlyfiles))
print (onlyfiles[:2])

onlyfiles.sort()
print (onlyfiles[:2])

/home/dongsung/Downloads/caltech-256-image-dataset/256_ObjectCategories/001.ak47
98
['001_0089.jpg', '001_0033.jpg']
['001_0001.jpg', '001_0002.jpg']


In [39]:
# save data
saved_dir ='/home/dongsung/Downloads/caltech-256-image-dataset/temp/'

In [49]:
# slpit data (train,val)
# val has 20 images from each class of train dataset
def split_data(data_dir,saved_dir):
    for i in range(len(object_categories)):
        # dataset
        category_dir = join(data_dir,object_categories[i])
        # read files
        onlyfiles = [f for f in listdir(category_dir) if isfile(join(category_dir, f))]
        onlyfiles.sort()
        
        # copy traing_data
        train_saved_dir=saved_dir+'train_no_resizing/'
        for image_file in onlyfiles[:-20]:
            shutil.copy(join(category_dir,image_file), join(train_saved_dir,image_file)) 
            
        # copy validation data
        
        val_saved_dir = saved_dir+'val/'
        for image_file in onlyfiles[-20:]:
            shutil.copy(join(category_dir,image_file), join(val_saved_dir,image_file)) 
        
#         break

In [50]:
split_data(data_dir,saved_dir)
#print(onlyfiles)
# print(onlyfiles[-20:])
# print(onlyfiles[:-20])
# val_saved_dir = saved_dir+'/val/'
# print (val_saved_dir)

In [86]:
# storing image as index and filename(including the path)
# data_set has index and filename
# label has index and lable
train_data=[]
train_labels=[]
val_data=[]
val_labels=[]

train_saved_dir ='/home/dongsung/Downloads/caltech-256-image-dataset/temp/train_no_resizing'
val_saved_dir ='/home/dongsung/Downloads/caltech-256-image-dataset/temp/val'

train_image_files = [f for f in listdir(train_saved_dir) if isfile(join(train_saved_dir, f))]
val_image_files = [f for f in listdir(val_saved_dir) if isfile(join(val_saved_dir, f))]
train_image_files.sort()
val_image_files.sort()
print(len(train_image_files), len(val_image_files), np.add(len(train_image_files),len(val_image_files)))
print(val_image_files[19:22])

# parsing logics for getting a label from a file name

# def readimages(data_dir,data_list,label_list):
#     for i in range(len(object_categories)):
#         # dataset
#         category_dir = join(data_dir,object_categories[i])
#         #print(category_dir)
#         onlyfiles = [f for f in listdir(category_dir) if isfile(join(category_dir, f))]
#         onlyfiles.sort()
#         num_images_per_class = len(onlyfiles)
#         print(i+1, num_images_per_class)
#         # handling dataset
#         for j in range(len(onlyfiles)):
#             train_data.append(onlyfiles[j])
#             train_labels.append(i+1)
            
# handling data, label from
train_data_images = [f for f in listdir(train_saved_dir) if isfile(join(train_saved_dir, f))]
train_data_images.sort()

for image_file in train_data_images:
    train_data.append(image_file)
    label = int(image_file.split('_')[0])
    train_labels.append(label)
    
val_data_images = [f for f in listdir(val_saved_dir) if isfile(join(val_saved_dir, f))]
val_data_images.sort()
    
for image_file in val_data_images:
    val_data.append(image_file)
    label = int(image_file.split('_')[0])
    val_labels.append(label)    


arr_indexes = np.arange(len(train_data))
print(arr_indexes)
# shuffle
np.random.shuffle(arr_indexes)
print(arr_indexes)

for i in arr_indexes[0:5]:
    print(train_data[i],train_labels[i])


# index handlig for data_provider
# batch_x = np.zeros((current_batch_size,) + self.image_shape, dtype=K.floatx())
#         batch_logits = np.zeros((current_batch_size, self.num_class), dtype=K.floatx())
#         grayscale = self.color_mode == 'grayscale'
#         # build batch of image data
#         for i, j in enumerate(index_array):
#             fname = self.filenames[j]
#             img = load_img(os.path.join(self.directory, fname),
#                            grayscale=grayscale,
#                            target_size=self.target_size)
#             x = img_to_array(img, data_format=self.data_format)
#             x = self.image_data_generator.random_transform(x)
#             x = self.image_data_generator.standardize(x)
#             batch_x[i] = x
            batch_logits[i] = self.logits_dict[fname]
    
    
    for i, label in enumerate(self.classes[index_array]):
                batch_y[i, label] = 1.

25468 5139 30607
['001_0098.jpg', '002_0078.jpg', '002_0079.jpg']
[    0     1     2 ... 25465 25466 25467]
[18026 21009  9244 ... 10397  2164 10072]
192_0026.jpg 192
228_0018.jpg 228
103_0084.jpg 103
009_0021.jpg 9
136_0066.jpg 136


In [ ]:
def data_generator(data, labels, batch_size=32, input_shape=(299,299,3),n_classes=10, shuffle=True):
    
    num_data = len(data)
    arr_indexes = np.arange(num_data)
    
    # shuffle
    if shuffle:
        np.random.shuffle(arr_indexes)
    
    num_batch = num_data/batch_size
    if (num_data/batch_size) > 0:
        num_batch = num_batch+1
    
    batch_x = np.zeros((batch_size,)+ input_shape)
    batch_y = np.zeros((batch_size,)+ n_classes)
    
    offset=0
    end =0
    
    for i in range(num_batch):
        
        offset=end
        end=batch_size+offsest
        if end > num_data:
            end = num_data

        batch_arr_indexes = arr_indexes[offset:end]
        
        # preparing the batch and yield batches
        for i, idx in enumerate(batch_arr_indexes):
            fname = data[idx]
            # image load from index
                   
            # data resizing
    #         img = load_img(os.path.join(self.directory, fname),
    #                            grayscale=grayscale,
    #                            target_size=self.target_size)

            label = labes[idx]
            batch_y[i, label]= 1

        yield batch_x, batch_y

In [87]:
indexes = np.arange(10)
print(indexes)
np.random.shuffle(indexes)
print(indexes)
test = np.zeros((32,)+(299,299,3))
print(np.shape(test))

[0 1 2 3 4 5 6 7 8 9]
[7 1 9 6 2 5 0 3 4 8]
(32, 299, 299, 3)


In [80]:
# readimages(data_dir)
# print(len(train_data), len(train_labels))
# for i in range(90,110):
#     print (train_data[i],train_labels[i] )

# M = pd.DataFrame(train_metadata)
# M.columns = ['directory', 'img_name', 'height', 'width', 'channels', 'byte_size', 'bit_depth']

# M['category_name'] = M.directory.apply(lambda x: x.split('.')[-1].lower())
# M['img_extension'] = M.img_name.apply(lambda x: x.split('.')[-1])
# M['category_number'] = M.directory.apply(lambda x: int(x.split('.')[0]))

# # remove '101' from some category names
# M.category_name = M.category_name.apply(lambda x: x[:-4] if '101' in x else 
print(train_data[70:102],train_labels[70:102])

['001_0071.jpg', '001_0072.jpg', '001_0073.jpg', '001_0074.jpg', '001_0075.jpg', '001_0076.jpg', '001_0077.jpg', '001_0078.jpg', '002_0001.jpg', '002_0002.jpg', '002_0003.jpg', '002_0004.jpg', '002_0005.jpg', '002_0006.jpg', '002_0007.jpg', '002_0008.jpg', '002_0009.jpg', '002_0010.jpg', '002_0011.jpg', '002_0012.jpg', '002_0013.jpg', '002_0014.jpg', '002_0015.jpg', '002_0016.jpg', '002_0017.jpg', '002_0018.jpg', '002_0019.jpg', '002_0020.jpg', '002_0021.jpg', '002_0022.jpg', '002_0023.jpg', '002_0024.jpg'] [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [ ]:
def readimages():
	'''
	Goes through every image and gets the image, putting them into an array
	Args:
		None
	Returns:
		data: array of information including:
			image: string
			shape: int 
			label: index from 0 to 256 for the classes
	'''
	data = []
	j = 0
	object_dir = os.path.join(main_dir, '256_ObjectCategories')
	objectCategories = os.listdir(object_dir)
	for i in range(len(objectCategories)):
		label = i
		examp_dir = os.path.join(object_dir, objectCategories[i])
		examples = os.listdir(examp_dir)
		print 'compiling data: %d/%d'%(i+1, len(objectCategories))
		for examp in examples:
			image_dir = os.path.join(examp_dir, examp)
			image, shape = get_image(image_dir)
			try:
				data[j]
			except IndexError:
				data.append([])

			data[j].append([image, shape, label])
			j = (j+1)%num_tffile
	return data
