In [1]:
import numpy as np

In [22]:
a = np.random.rand(3,2)
b = np.random.rand(2,2)
c = []

print(a)
print(b)

[[0.11916354 0.00935769]
 [0.50139208 0.30204473]
 [0.34190585 0.98032303]]
[[0.13578243 0.87503173]
 [0.50204954 0.33548314]]


In [37]:
b2= np.random.rand(2,2)

In [10]:
for i in range(0,5):
    c.ap

0
1
2
3
4


In [12]:
np.append()

AxisError: axis 1 is out of bounds for array of dimension 1

In [18]:
c= np.stack(a)
print(c)

[[0.41399962 0.37813481]
 [0.1733906  0.58156499]
 [0.62257235 0.39419615]]


In [20]:
c = np.stack(b)
print(c)

[[0.78685516 0.17593261]
 [0.27882233 0.13330801]]


In [27]:
c=np.append(c,a)

In [28]:
print(c)

[0.11916354 0.00935769 0.50139208 0.30204473 0.34190585 0.98032303]


In [29]:
c=np.append(c,b)
print(c)

[0.11916354 0.00935769 0.50139208 0.30204473 0.34190585 0.98032303
 0.13578243 0.87503173 0.50204954 0.33548314]


In [32]:
d=np.reshape(c,(5,2))
print(d)

[[0.11916354 0.00935769]
 [0.50139208 0.30204473]
 [0.34190585 0.98032303]
 [0.13578243 0.87503173]
 [0.50204954 0.33548314]]


In [39]:
e= np.c_[b2,b]
print(e)
print(b2)

[[0.16674636 0.4438501  0.13578243 0.87503173]
 [0.27808818 0.29201852 0.50204954 0.33548314]]
[[0.16674636 0.4438501 ]
 [0.27808818 0.29201852]]
